In [23]:
import pandas as pd
import numpy as np

heroes = pd.read_csv('data/heroes.csv', sep=';', index_col=0)
heroes

,Identity,Birth place,Publisher,Height,Weight,Gender,First appearance,Eye color,Hair color,Strength,Intelligence
Name,,,,,,,,,,,
A-Bomb,Richard Milhouse Jones,"Scarsdale, Arizona",Marvel Comics,203.21,441.95,M,2008.0,Yellow,No Hair,100.0,moderate
Abraxas,Abraxas,Within Eternity,Marvel Comics,NaN,NaN,M,NaN,Blue,Black,100.0,high
Abomination,Emil Blonsky,"Zagreb, Yugoslavia",Marvel Comics,203.04,441.98,M,NaN,Green,No Hair,80.0,good
Adam Monroe,NaN,NaN,NBC - Heroes,NaN,NaN,M,NaN,Blue,Blond,10.0,good
Agent 13,Sharon Carter,NaN,Marvel Comics,173.41,61.03,F,NaN,Blue,Blond,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Alan Scott,Alan Ladd Wellington Scott,Gotham City,DC Comics,180.98,90.81,M,1940.0,Blue,Blond,80.0,good
Amazo,NaN,NaN,DC Comics,257.49,173.95,M,1960.0,Red,NaN,100.0,good
Ant-Man,Hank Pym,"Elmsford, New York",Marvel Comics,211.74,122.44,M,1962.0,Blue,Blond,20.0,high
Ajax,Francis,NaN,Marvel Comics,193.34,90.63,M,1998.0,Brown,Black,50.0,average
Alex Mercer,Alexander J. Mercer,NaN,Wildstorm,NaN,NaN,M,NaN,NaN,NaN,80.0,average

In [24]:
marvel_heroes = heroes[heroes['Publisher']=='Marvel Comics']
p_marvel = len(marvel_heroes) / len(heroes)
p_marvel

0.527891156462585

In [25]:
black_eyes_heroes = heroes[heroes['Eye color']=='Black']
p_blackeyes = len(black_eyes_heroes) / len(heroes)
p_blackeyes

0.0326530612244898

In [26]:
blackeyes_and_marvel_heroes = heroes[(heroes['Publisher']=='Marvel Comics') & \
                                     (heroes['Eye color']=='Black')]

p_blackeyes_given_marvel = len(blackeyes_and_marvel_heroes) / len(marvel_heroes)
p_blackeyes_given_marvel

0.028350515463917526

In [27]:
p_blackeyes_given_marvel * p_marvel / p_blackeyes

0.45833333333333326

In [28]:
nonmarvel_heroes = heroes[heroes['Publisher']!='Marvel Comics']
blackeyes_and_nonmarvel_heroes = heroes[(heroes['Publisher']!='Marvel Comics') & \
                                        (heroes['Eye color']=='Black')]

p_notmarvel = len(nonmarvel_heroes) / len(heroes)
p_blackeyes_given_notmarvel = len(blackeyes_and_nonmarvel_heroes) / len(nonmarvel_heroes)

p_blackeyes_given_notmarvel * p_notmarvel / p_blackeyes

0.5416666666666665

In [29]:
black_eyes_and_hair_heroes = heroes[(heroes['Eye color']=='Black') & \
                                    (heroes['Hair color']=='Black')]

p_blackeyes_and_black_hair = len(black_eyes_and_hair_heroes) / len(heroes)

blackhair_and_marvel_heroes = heroes[(heroes['Publisher']=='Marvel Comics') & \
                                     (heroes['Hair color']=='Black')]
p_blackhair_given_marvel = len(blackhair_and_marvel_heroes) / len(marvel_heroes)

p_blackeyes_given_marvel * p_blackhair_given_marvel * p_marvel \
     / p_blackeyes_and_black_hair

0.2190721649484536

In [30]:
features = ['Height', 'Weight', 'Gender', 'First appearance',
            'Hair color', 'Eye color', 'Strength', 'Intelligence']
heroes_cleaned = heroes.dropna()
X = heroes_cleaned[features].copy()

In [31]:
from sklearn.preprocessing import LabelEncoder

n = 4

In [32]:
X

,Height,Weight,Gender,First appearance,Hair color,Eye color,Strength,Intelligence
Name,,,,,,,,
A-Bomb,203.21,441.95,M,2008.0,No Hair,Yellow,100.0,moderate
Lady Deathstrike,175.85,58.89,F,1985.0,Black,Brown,30.0,good
Absorbing Man,193.36,122.28,M,1964.0,No Hair,Blue,80.0,moderate
X-Man,175.82,61.80,M,1995.0,Brown,Blue,55.0,high
Adam Strange,185.10,88.92,M,1986.0,Blond,Blue,10.0,good
...,...,...,...,...,...,...,...,...
Ant-Man II,183.67,86.28,M,1979.0,Blond,Blue,20.0,good
Annihilus,180.94,90.11,M,1968.0,No Hair,Green,80.0,good
Angel,183.05,68.99,M,1969.0,Blond,Blue,15.0,good
Alan Scott,180.98,90.81,M,1940.0,Blond,Blue,80.0,good
Ant-Man,211.74,122.44,M,1962.0,Blond,Blue,20.0,high

In [33]:
X['Height'] = pd.qcut(X['Height'], n, labels=range(n))
X['Weight'] = pd.qcut(X['Weight'], n, labels=range(n))

gender_encoder = LabelEncoder()
gender_encoder.fit(X['Gender'])
X['Gender'] = gender_encoder.transform(X['Gender'])

In [34]:
X['First appearance'] = pd.qcut(X['First appearance'],
                                n,
                                labels=range(n))

hair_encoder = LabelEncoder()
hair_encoder.fit(X['Hair color'])
X['Hair color'] = hair_encoder.transform(X['Hair color'])

eye_encoder = LabelEncoder()
eye_encoder.fit(X['Eye color'])
X['Eye color'] = eye_encoder.transform(X['Eye color'])

X['Strength'] = pd.qcut(X['Strength'], n, labels=range(n))

In [35]:
intelligence_encoder = LabelEncoder()
intelligence_encoder.fit(X['Intelligence'])
X['Intelligence'] = intelligence_encoder.transform(X['Intelligence'])